apiVersion: v1
kind: Secret
metadata:
  name: filevault-secrets
type: Opaque
stringData:
  azure-storage-account-name: "filevaultstorage2025"
  azure-storage-account-key: "{{AZURE_STORAGE_ACCOUNT_KEY}}"
  azure-container-name: "$web"
