apiVersion: v1
kind: Secret
metadata:
  name: filevault-secrets
type: Opaque
stringData:
  azure-storage-account-name: "filevaultstorage2025"
  azure-storage-account-key: "{{AZURE_STORAGE_ACCOUNT_KEY}}"
  azure-container-name: "$web"
  applicationinsights-connection-string: "InstrumentationKey=fda735b5-75d0-479c-bdf2-b430362d4817;IngestionEndpoint=https://uksouth-1.in.applicationinsights.azure.com/;LiveEndpoint=https://uksouth.livediagnostics.monitor.azure.com/;ApplicationId=5279b986-f85b-4b59-ab08-3286bb303889"
